import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  BookOpen, 
  Brain, 
  FileText, 
  Star, 
  Clock, 
  TrendingUp,
  Plus,
  Download,
  Share,
  Trash2,
  Eye,
  Lightbulb,
  Sparkles,
  Search,
  Filter,
  Calendar,
  User,
  Target,
  BarChart3,
  Zap,
  MessageSquare,
  Map
} from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Layout from "@/components/Layout";
import { FeatureTooltip, AdminTooltip } from "@/components/SmartTooltip";

interface StudyResource {
  id: string;
  title: string;
  type: string;
  content: string;
  quizId?: string;
  quizTitle?: string;
  sourceType?: string;
  sourceId?: string;
  createdFor?: string;
  createdAt: string;
  lastAccessedAt: string;
  accessCount: number;
  rating: number;
  isAutoGenerated: boolean;
  tags?: string[];
}

const studyResourceTypes = [
  { value: 'study_guide', label: 'Study Guide', icon: Lightbulb, description: 'Comprehensive study plan and overview', color: 'bg-blue-500' },
  { value: 'flashcards', label: 'Flashcards', icon: Brain, description: 'Interactive question and answer cards', color: 'bg-green-500' },
  { value: 'practice_questions', label: 'Practice Questions', icon: BookOpen, description: 'Additional questions for practice', color: 'bg-purple-500' },
  { value: 'summary', label: 'Summary', icon: FileText, description: 'Condensed overview of key concepts', color: 'bg-orange-500' },
  { value: 'concept_map', label: 'Concept Map', icon: Map, description: 'Visual representation of relationships', color: 'bg-pink-500' },
  { value: 'study_schedule', label: 'Study Schedule', icon: Calendar, description: 'Personalized study timeline', color: 'bg-indigo-500' },
  { value: 'performance_analysis', label: 'Performance Analysis', icon: BarChart3, description: 'AI insights on your performance', color: 'bg-red-500' },
  { value: 'learning_plan', label: 'Learning Plan', icon: Target, description: 'Adaptive learning recommendations', color: 'bg-cyan-500' },
];

const getResourceIcon = (type: string) => {
  const resourceType = studyResourceTypes.find(t => t.value === type);
  return resourceType ? resourceType.icon : FileText;
};

const getResourceColor = (type: string) => {
  const resourceType = studyResourceTypes.find(t => t.value === type);
  return resourceType ? resourceType.color : 'bg-gray-500';
};

const formatTimeAgo = (dateString: string) => {
  const date = new Date(dateString);
  const now = new Date();
  const diffInHours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
  
  if (diffInHours < 1) return 'Just now';
  if (diffInHours < 24) return `${diffInHours}h ago`;
  if (diffInHours < 168) return `${Math.floor(diffInHours / 24)}d ago`;
  return date.toLocaleDateString();
};

export default function StudyResources() {
  const [selectedType, setSelectedType] = useState<string>('');
  const [selectedQuiz, setSelectedQuiz] = useState<string>('');
  const [customPrompt, setCustomPrompt] = useState<string>('');
  const [title, setTitle] = useState<string>('');
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [activeTab, setActiveTab] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState('all');
  const [referenceLinks, setReferenceLinks] = useState<string[]>([]);
  const [newReferenceLink, setNewReferenceLink] = useState<string>('');
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const { toast } = useToast();

  // Fetch both study aids and AI resources (unified)
  const { data: studyResources = [], isLoading } = useQuery({
    queryKey: ['/api/ai/resources'],
  });

  const { data: availableQuizzes = [] } = useQuery({
    queryKey: ['/api/quizzes/available'],
  });

  const createResourceMutation = useMutation({
    mutationFn: async (data: { 
      type: string; 
      quizId?: string; 
      title: string; 
      customPrompt?: string;
      referenceLinks?: string[];
      uploadedFiles?: File[];
    }) => {
      const response = await apiRequest('/api/study-aids/generate', { 
        method: 'POST', 
        body: JSON.stringify(data) 
      });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/ai/resources'] });
      queryClient.invalidateQueries({ queryKey: ['/api/study-aids'] });
      setShowCreateDialog(false);
      setSelectedType('');
      setSelectedQuiz('');
      setCustomPrompt('');
      setTitle('');
      setReferenceLinks([]);
      setUploadedFiles([]);
      toast({
        title: "Success",
        description: "Study resource created successfully!",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "Failed to create study resource. Please try again.",
        variant: "destructive",
      });
    },
  });

  const filteredResources = studyResources.filter((resource: StudyResource) => {
    const matchesSearch = resource.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         resource.content.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesType = filterType === 'all' || resource.type === filterType;
    const matchesTab = activeTab === 'all' || 
                      (activeTab === 'auto' && resource.isAutoGenerated) ||
                      (activeTab === 'manual' && !resource.isAutoGenerated) ||
                      (activeTab === 'ai' && (resource.type === 'study_schedule' || resource.type === 'performance_analysis' || resource.type === 'learning_plan'));
    
    return matchesSearch && matchesType && matchesTab;
  });

  const handleCreateResource = () => {
    if (!selectedType || !title) {
      toast({
        title: "Error",
        description: "Please select a resource type and enter a title.",
        variant: "destructive",
      });
      return;
    }

    createResourceMutation.mutate({
      type: selectedType,
      quizId: selectedQuiz && selectedQuiz !== 'custom' ? selectedQuiz : undefined,
      title,
      customPrompt: customPrompt || undefined,
      referenceLinks: referenceLinks.filter(link => link.trim() !== ''),
      uploadedFiles,
    });
  };

  const handleExportResource = async (resource: StudyResource, format: 'pdf' | 'txt' | 'csv' | 'json') => {
    try {
      const response = await apiRequest(`/api/study-resources/${resource.id}/export?format=${format}`, {
        method: 'GET',
      });
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${resource.title}.${format}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({
        title: "Success",
        description: `Resource exported as ${format.toUpperCase()}`,
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to export resource",
        variant: "destructive",
      });
    }
  };

  const handleShareResource = async (resource: StudyResource) => {
    try {
      const response = await apiRequest(`/api/study-resources/${resource.id}/share`, {
        method: 'POST',
        body: JSON.stringify({ shareType: 'link' }),
      });
      
      const data = await response.json();
      
      if (navigator.share) {
        await navigator.share({
          title: resource.title,
          text: `Check out this study resource: ${resource.title}`,
          url: data.shareUrl,
        });
      } else {
        await navigator.clipboard.writeText(data.shareUrl);
        toast({
          title: "Success",
          description: "Share link copied to clipboard",
        });
      }
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to share resource",
        variant: "destructive",
      });
    }
  };

  const [viewingResource, setViewingResource] = useState<StudyResource | null>(null);
  const [selectedResources, setSelectedResources] = useState<string[]>([]);

  const handleViewResource = (resource: StudyResource) => {
    setViewingResource(resource);
  };

  const handleSelectResource = (resourceId: string, isSelected: boolean) => {
    if (isSelected) {
      setSelectedResources(prev => [...prev, resourceId]);
    } else {
      setSelectedResources(prev => prev.filter(id => id !== resourceId));
    }
  };

  const handleSelectAll = () => {
    if (selectedResources.length === filteredResources.length) {
      setSelectedResources([]);
    } else {
      setSelectedResources(filteredResources.map(r => r.id));
    }
  };

  const handleBulkExport = async (format: 'pdf' | 'txt' | 'csv' | 'json') => {
    try {
      const response = await apiRequest('/api/study-resources/bulk-export', {
        method: 'POST',
        body: JSON.stringify({
          resourceIds: selectedResources,
          format,
        }),
      });
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `study-resources-bulk.${format}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({
        title: "Success",
        description: `${selectedResources.length} resources exported as ${format.toUpperCase()}`,
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to export resources",
        variant: "destructive",
      });
    }
  };

  const handleBulkDelete = async () => {
    try {
      await apiRequest('/api/study-resources/bulk-delete', {
        method: 'POST',
        body: JSON.stringify({
          resourceIds: selectedResources,
        }),
      });
      
      queryClient.invalidateQueries({ queryKey: ['/api/ai/resources'] });
      setSelectedResources([]);
      
      toast({
        title: "Success",
        description: `${selectedResources.length} resources deleted`,
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to delete resources",
        variant: "destructive",
      });
    }
  };

  const addReferenceLink = () => {
    if (newReferenceLink.trim() && !referenceLinks.includes(newReferenceLink.trim())) {
      setReferenceLinks([...referenceLinks, newReferenceLink.trim()]);
      setNewReferenceLink('');
    }
  };

  const removeReferenceLink = (linkToRemove: string) => {
    setReferenceLinks(referenceLinks.filter(link => link !== linkToRemove));
  };

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        <div className="flex flex-col space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Study Resources</h1>
              <p className="text-gray-600 dark:text-gray-300 mt-2">
                Manage your study materials, AI-generated resources, and learning aids
              </p>
            </div>
            <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
              <DialogTrigger asChild>
                <Button className="bg-blue-600 hover:bg-blue-700 text-white">
                  <Plus className="h-4 w-4 mr-2" />
                  Create Resource
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>Create New Study Resource</DialogTitle>
                  <DialogDescription>
                    Generate a new study resource with AI assistance
                  </DialogDescription>
                </DialogHeader>
                
                <div className="space-y-4">
                  <div>
                    <Label htmlFor="resource-type">Resource Type</Label>
                    <Select value={selectedType} onValueChange={setSelectedType}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select resource type" />
                      </SelectTrigger>
                      <SelectContent>
                        {studyResourceTypes.map((type) => (
                          <SelectItem key={type.value} value={type.value}>
                            <div className="flex items-center">
                              <type.icon className="h-4 w-4 mr-2" />
                              {type.label}
                            </div>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label htmlFor="title">Title</Label>
                    <Input
                      id="title"
                      value={title}
                      onChange={(e) => setTitle(e.target.value)}
                      placeholder="Enter resource title"
                    />
                  </div>

                  <div>
                    <Label htmlFor="quiz-select">Quiz/Topic (Optional)</Label>
                    <Select value={selectedQuiz} onValueChange={setSelectedQuiz}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select quiz or enter custom topic" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="custom">Custom Topic</SelectItem>
                        {availableQuizzes.map((quiz: any) => (
                          <SelectItem key={quiz.id} value={quiz.id}>
                            {quiz.title}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label htmlFor="custom-prompt">Custom Instructions (Optional)</Label>
                    <Textarea
                      id="custom-prompt"
                      value={customPrompt}
                      onChange={(e) => setCustomPrompt(e.target.value)}
                      placeholder="Enter specific instructions for AI generation..."
                      rows={3}
                    />
                  </div>

                  {/* Reference Links */}
                  <div>
                    <Label>Reference Links (Optional)</Label>
                    <div className="flex gap-2 mb-2">
                      <Input
                        value={newReferenceLink}
                        onChange={(e) => setNewReferenceLink(e.target.value)}
                        placeholder="Enter reference URL"
                      />
                      <Button type="button" onClick={addReferenceLink} variant="outline">
                        Add
                      </Button>
                    </div>
                    {referenceLinks.length > 0 && (
                      <div className="space-y-1">
                        {referenceLinks.map((link, index) => (
                          <div key={index} className="flex items-center justify-between bg-gray-50 dark:bg-gray-800 p-2 rounded">
                            <span className="text-sm truncate">{link}</span>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() => removeReferenceLink(link)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="flex justify-end space-x-2">
                    <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
                      Cancel
                    </Button>
                    <Button onClick={handleCreateResource} disabled={createResourceMutation.isPending}>
                      {createResourceMutation.isPending ? 'Creating...' : 'Create Resource'}
                    </Button>
                  </div>
                </div>
              </DialogContent>
            </Dialog>
          </div>

          {/* Filters and Bulk Actions */}
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
                <Input
                  placeholder="Search resources..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
            <Select value={filterType} onValueChange={setFilterType}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Filter by type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                {studyResourceTypes.map((type) => (
                  <SelectItem key={type.value} value={type.value}>
                    {type.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            {/* Bulk Actions */}
            {selectedResources.length > 0 && (
              <div className="flex gap-2">
                <Dialog>
                  <DialogTrigger asChild>
                    <Button variant="outline" size="sm">
                      <Download className="h-4 w-4 mr-2" />
                      Export ({selectedResources.length})
                    </Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>Bulk Export Resources</DialogTitle>
                      <DialogDescription>
                        Export {selectedResources.length} selected resources
                      </DialogDescription>
                    </DialogHeader>
                    <div className="grid grid-cols-2 gap-4">
                      <Button 
                        variant="outline" 
                        onClick={() => handleBulkExport('pdf')}
                        className="flex items-center justify-center"
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        PDF
                      </Button>
                      <Button 
                        variant="outline" 
                        onClick={() => handleBulkExport('txt')}
                        className="flex items-center justify-center"
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        Text
                      </Button>
                      <Button 
                        variant="outline" 
                        onClick={() => handleBulkExport('csv')}
                        className="flex items-center justify-center"
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        CSV
                      </Button>
                      <Button 
                        variant="outline" 
                        onClick={() => handleBulkExport('json')}
                        className="flex items-center justify-center"
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        JSON
                      </Button>
                    </div>
                  </DialogContent>
                </Dialog>
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={handleBulkDelete}
                  className="text-red-600 hover:text-red-700"
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  Delete ({selectedResources.length})
                </Button>
              </div>
            )}
          </div>

          {/* Tabs */}
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="all">All Resources</TabsTrigger>
              <TabsTrigger value="manual">Manual</TabsTrigger>
              <TabsTrigger value="auto">Auto-Generated</TabsTrigger>
              <TabsTrigger value="ai">AI Insights</TabsTrigger>
            </TabsList>

            <TabsContent value={activeTab} className="space-y-4">
              {isLoading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {[...Array(6)].map((_, i) => (
                    <Card key={i} className="animate-pulse">
                      <CardHeader>
                        <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                        <div className="h-3 bg-gray-200 rounded w-1/2"></div>
                      </CardHeader>
                      <CardContent>
                        <div className="h-3 bg-gray-200 rounded w-full mb-2"></div>
                        <div className="h-3 bg-gray-200 rounded w-2/3"></div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              ) : filteredResources.length > 0 ? (
                <div className="space-y-4">
                  {/* Select All */}
                  <div className="flex items-center gap-2 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                    <input
                      type="checkbox"
                      checked={selectedResources.length === filteredResources.length}
                      onChange={handleSelectAll}
                      className="rounded border-gray-300"
                    />
                    <Label className="text-sm">
                      Select All ({filteredResources.length} resources)
                    </Label>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {filteredResources.map((resource: StudyResource) => {
                      const IconComponent = getResourceIcon(resource.type);
                      const colorClass = getResourceColor(resource.type);
                      const isSelected = selectedResources.includes(resource.id);
                      
                      return (
                        <Card key={resource.id} className={`hover:shadow-lg transition-shadow ${isSelected ? 'ring-2 ring-blue-500' : ''}`}>
                        <CardHeader className="pb-3">
                          <div className="flex items-start justify-between">
                            <div className="flex items-center space-x-2">
                              <input
                                type="checkbox"
                                checked={isSelected}
                                onChange={(e) => handleSelectResource(resource.id, e.target.checked)}
                                className="rounded border-gray-300"
                              />
                              <div className={`p-2 rounded-lg ${colorClass}`}>
                                <IconComponent className="h-4 w-4 text-white" />
                              </div>
                              <div>
                                <CardTitle className="text-lg">{resource.title}</CardTitle>
                                <Badge variant={resource.isAutoGenerated ? "default" : "secondary"} className="mt-1">
                                  {resource.isAutoGenerated ? 'Auto-Generated' : 'Manual'}
                                </Badge>
                              </div>
                            </div>
                            <div className="flex items-center space-x-1">
                              <Star className="h-4 w-4 text-yellow-400 fill-current" />
                              <span className="text-sm">{resource.rating}</span>
                            </div>
                          </div>
                        </CardHeader>
                        <CardContent>
                          <p className="text-gray-600 dark:text-gray-300 text-sm mb-3 line-clamp-2">
                            {resource.content}
                          </p>
                          
                          {resource.quizTitle && (
                            <div className="flex items-center text-sm text-gray-500 mb-2">
                              <BookOpen className="h-4 w-4 mr-1" />
                              <span>{resource.quizTitle}</span>
                            </div>
                          )}
                          
                          <div className="flex items-center justify-between text-sm text-gray-500">
                            <div className="flex items-center space-x-4">
                              <div className="flex items-center">
                                <Clock className="h-4 w-4 mr-1" />
                                <span>{formatTimeAgo(resource.createdAt)}</span>
                              </div>
                              <div className="flex items-center">
                                <Eye className="h-4 w-4 mr-1" />
                                <span>{resource.accessCount}</span>
                              </div>
                            </div>
                          </div>
                          
                          {resource.tags && resource.tags.length > 0 && (
                            <div className="flex flex-wrap gap-1 mt-2">
                              {resource.tags.map((tag, index) => (
                                <Badge key={index} variant="outline" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                            </div>
                          )}
                          
                          <Separator className="my-3" />
                          
                          <div className="flex items-center justify-between">
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => handleViewResource(resource)}
                            >
                              <Eye className="h-4 w-4 mr-1" />
                              View
                            </Button>
                            <div className="flex space-x-2">
                              <Dialog>
                                <DialogTrigger asChild>
                                  <Button variant="outline" size="sm">
                                    <Download className="h-4 w-4" />
                                  </Button>
                                </DialogTrigger>
                                <DialogContent>
                                  <DialogHeader>
                                    <DialogTitle>Export Resource</DialogTitle>
                                    <DialogDescription>
                                      Choose format to export "{resource.title}"
                                    </DialogDescription>
                                  </DialogHeader>
                                  <div className="grid grid-cols-2 gap-4">
                                    <Button 
                                      variant="outline" 
                                      onClick={() => handleExportResource(resource, 'pdf')}
                                      className="flex items-center justify-center"
                                    >
                                      <FileText className="h-4 w-4 mr-2" />
                                      PDF
                                    </Button>
                                    <Button 
                                      variant="outline" 
                                      onClick={() => handleExportResource(resource, 'txt')}
                                      className="flex items-center justify-center"
                                    >
                                      <FileText className="h-4 w-4 mr-2" />
                                      Text
                                    </Button>
                                    <Button 
                                      variant="outline" 
                                      onClick={() => handleExportResource(resource, 'csv')}
                                      className="flex items-center justify-center"
                                    >
                                      <FileText className="h-4 w-4 mr-2" />
                                      CSV
                                    </Button>
                                    <Button 
                                      variant="outline" 
                                      onClick={() => handleExportResource(resource, 'json')}
                                      className="flex items-center justify-center"
                                    >
                                      <FileText className="h-4 w-4 mr-2" />
                                      JSON
                                    </Button>
                                  </div>
                                </DialogContent>
                              </Dialog>
                              <Button 
                                variant="outline" 
                                size="sm"
                                onClick={() => handleShareResource(resource)}
                              >
                                <Share className="h-4 w-4" />
                              </Button>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                  </div>
                </div>
              ) : (
                <Card className="text-center py-12">
                  <CardContent>
                    <div className="flex flex-col items-center space-y-4">
                      <div className="p-4 bg-gray-100 dark:bg-gray-800 rounded-full">
                        <Sparkles className="h-8 w-8 text-gray-400" />
                      </div>
                      <div>
                        <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
                          No Study Resources Found
                        </h3>
                        <p className="text-gray-600 dark:text-gray-300 mb-4">
                          {searchQuery || filterType !== 'all' 
                            ? 'No resources match your current filters' 
                            : 'Create your first study resource to get started'}
                        </p>
                        <Button 
                          onClick={() => setShowCreateDialog(true)}
                          className="bg-blue-600 hover:bg-blue-700 text-white"
                        >
                          <Plus className="h-4 w-4 mr-2" />
                          Create Resource
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </div>

      {/* Resource Viewer Modal */}
      {viewingResource && (
        <Dialog open={!!viewingResource} onOpenChange={() => setViewingResource(null)}>
          <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                {(() => {
                  const IconComponent = getResourceIcon(viewingResource.type);
                  const colorClass = getResourceColor(viewingResource.type);
                  return (
                    <>
                      <div className={`p-2 rounded-lg ${colorClass}`}>
                        <IconComponent className="h-4 w-4 text-white" />
                      </div>
                      {viewingResource.title}
                    </>
                  );
                })()}
              </DialogTitle>
              <DialogDescription>
                <div className="flex items-center gap-4 text-sm text-gray-500 mt-2">
                  <div className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    {formatTimeAgo(viewingResource.createdAt)}
                  </div>
                  <div className="flex items-center gap-1">
                    <Eye className="h-4 w-4" />
                    {viewingResource.accessCount} views
                  </div>
                  <div className="flex items-center gap-1">
                    <Star className="h-4 w-4 text-yellow-400 fill-current" />
                    {viewingResource.rating}
                  </div>
                  <Badge variant={viewingResource.isAutoGenerated ? "default" : "secondary"}>
                    {viewingResource.isAutoGenerated ? 'Auto-Generated' : 'Manual'}
                  </Badge>
                </div>
              </DialogDescription>
            </DialogHeader>
            
            <div className="space-y-4">
              {viewingResource.quizTitle && (
                <div className="flex items-center gap-2 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                  <BookOpen className="h-4 w-4 text-blue-500" />
                  <span className="text-sm">Related to: {viewingResource.quizTitle}</span>
                </div>
              )}
              
              <div className="prose dark:prose-invert max-w-none">
                <div className="whitespace-pre-wrap text-sm leading-relaxed">
                  {viewingResource.content}
                </div>
              </div>
              
              {viewingResource.tags && viewingResource.tags.length > 0 && (
                <div className="flex flex-wrap gap-2 pt-4 border-t">
                  <span className="text-sm font-medium">Tags:</span>
                  {viewingResource.tags.map((tag, index) => (
                    <Badge key={index} variant="outline" className="text-xs">
                      {tag}
                    </Badge>
                  ))}
                </div>
              )}
              
              <div className="flex justify-between items-center pt-4 border-t">
                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => handleShareResource(viewingResource)}
                  >
                    <Share className="h-4 w-4 mr-1" />
                    Share
                  </Button>
                  <Dialog>
                    <DialogTrigger asChild>
                      <Button variant="outline" size="sm">
                        <Download className="h-4 w-4 mr-1" />
                        Export
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Export Resource</DialogTitle>
                        <DialogDescription>
                          Choose format to export "{viewingResource.title}"
                        </DialogDescription>
                      </DialogHeader>
                      <div className="grid grid-cols-2 gap-4">
                        <Button 
                          variant="outline" 
                          onClick={() => handleExportResource(viewingResource, 'pdf')}
                          className="flex items-center justify-center"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          PDF
                        </Button>
                        <Button 
                          variant="outline" 
                          onClick={() => handleExportResource(viewingResource, 'txt')}
                          className="flex items-center justify-center"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          Text
                        </Button>
                        <Button 
                          variant="outline" 
                          onClick={() => handleExportResource(viewingResource, 'csv')}
                          className="flex items-center justify-center"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          CSV
                        </Button>
                        <Button 
                          variant="outline" 
                          onClick={() => handleExportResource(viewingResource, 'json')}
                          className="flex items-center justify-center"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          JSON
                        </Button>
                      </div>
                    </DialogContent>
                  </Dialog>
                </div>
                <Button onClick={() => setViewingResource(null)}>
                  Close
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      )}
    </Layout>
  );
}